<?php

// Generated by Haxe 3.4.0
class decode_bit_reader_BrotliBitReader {
	public function __construct() {
		if(!php_Boot::$skip_constructor) {
		$this->buf_off = 0;
		$this1 = (new _hx_array(array()));
		$this1->length = 8320;
		$this->buf_ = $this1;
	}}
	public $val_;
	public $pos_;
	public $bit_pos_;
	public $bit_end_pos_;
	public $eos_;
	public $buf_ptr_;
	public $buf_ptr_off;
	public $input_;
	public $finish_;
	public $tmp_bytes_read_;
	public $buf_;
	public $buf_off;
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return 'decode.bit_reader.BrotliBitReader'; }
}
