// Generated by Haxe 3.4.0

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace encode {
	public class Dictionary_hash : global::haxe.lang.HxObject {
		
		static Dictionary_hash() {
			global::encode.Dictionary_hash.kStaticDictionaryHash = new global::Array<uint>(new uint[]{});
		}
		
		
		public Dictionary_hash(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Dictionary_hash() {
			global::encode.Dictionary_hash.__hx_ctor_encode_Dictionary_hash(this);
		}
		
		
		public static void __hx_ctor_encode_Dictionary_hash(global::encode.Dictionary_hash __hx_this) {
		}
		
		
		public static global::Array<uint> kStaticDictionaryHash;
		
	}
}


