// Generated by Haxe 3.4.0

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace encode {
	public class Static_dict_lut : global::haxe.lang.HxObject {
		
		static Static_dict_lut() {
			unchecked {
				global::encode.Static_dict_lut.kDictNumBits = 15;
				global::encode.Static_dict_lut.kDictHashMul32 = ((uint) (506832829) );
				global::encode.Static_dict_lut.kStaticDictionaryBuckets = new global::Array<uint>(new uint[]{});
				global::encode.Static_dict_lut.kStaticDictionaryWords = new global::Array<object>(new object[]{});
			}
		}
		
		
		public Static_dict_lut(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Static_dict_lut() {
			global::encode.Static_dict_lut.__hx_ctor_encode_Static_dict_lut(this);
		}
		
		
		public static void __hx_ctor_encode_Static_dict_lut(global::encode.Static_dict_lut __hx_this) {
		}
		
		
		public static int kDictNumBits;
		
		public static uint kDictHashMul32;
		
		public static global::Array<uint> kStaticDictionaryBuckets;
		
		public static global::Array<object> kStaticDictionaryWords;
		
	}
}


