// Generated by Haxe 3.4.0
package decode;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class State extends haxe.lang.HxObject
{
	public State(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public State()
	{
		//line 41 "C:\\Users\\Dominik\\Brotli\\src\\decode\\State.hx"
		decode.State.__hx_ctor_decode_State(this);
	}
	
	
	public static void __hx_ctor_decode_State(decode.State __hx_this)
	{
	}
	
	
	public static void BrotliStateInit(decode.state.BrotliState s)
	{
		//line 13 "C:\\Users\\Dominik\\Brotli\\src\\decode\\State.hx"
		s.state = ((int) (0) );
		//line 14 "C:\\Users\\Dominik\\Brotli\\src\\decode\\State.hx"
		((int[]) (s.sub_state) )[0] = ((int) (50) );
		//line 15 "C:\\Users\\Dominik\\Brotli\\src\\decode\\State.hx"
		((int[]) (s.sub_state) )[1] = ((int) (50) );
		//line 17 "C:\\Users\\Dominik\\Brotli\\src\\decode\\State.hx"
		s.block_type_trees = null;
		//line 18 "C:\\Users\\Dominik\\Brotli\\src\\decode\\State.hx"
		s.block_len_trees = null;
		//line 19 "C:\\Users\\Dominik\\Brotli\\src\\decode\\State.hx"
		s.ringbuffer = null;
		//line 21 "C:\\Users\\Dominik\\Brotli\\src\\decode\\State.hx"
		s.context_map = null;
		//line 22 "C:\\Users\\Dominik\\Brotli\\src\\decode\\State.hx"
		s.context_modes = null;
		//line 23 "C:\\Users\\Dominik\\Brotli\\src\\decode\\State.hx"
		s.dist_context_map = null;
		//line 24 "C:\\Users\\Dominik\\Brotli\\src\\decode\\State.hx"
		s.context_map_slice = null;
		//line 25 "C:\\Users\\Dominik\\Brotli\\src\\decode\\State.hx"
		s.context_map_slice_off = 0;
		//line 26 "C:\\Users\\Dominik\\Brotli\\src\\decode\\State.hx"
		s.dist_context_map_slice = null;
		//line 27 "C:\\Users\\Dominik\\Brotli\\src\\decode\\State.hx"
		s.dist_context_map_slice_off = 0;
		//line 29 "C:\\Users\\Dominik\\Brotli\\src\\decode\\State.hx"
		{
			//line 29 "C:\\Users\\Dominik\\Brotli\\src\\decode\\State.hx"
			int _g = 0;
			//line 29 "C:\\Users\\Dominik\\Brotli\\src\\decode\\State.hx"
			while (( _g < 3 ))
			{
				//line 29 "C:\\Users\\Dominik\\Brotli\\src\\decode\\State.hx"
				int i = _g++;
				//line 30 "C:\\Users\\Dominik\\Brotli\\src\\decode\\State.hx"
				((decode.huffman.HuffmanTreeGroup[]) (s.hgroup) )[i].codes = null;
				//line 31 "C:\\Users\\Dominik\\Brotli\\src\\decode\\State.hx"
				((decode.huffman.HuffmanTreeGroup[]) (s.hgroup) )[i].htrees = null;
			}
			
		}
		
		//line 34 "C:\\Users\\Dominik\\Brotli\\src\\decode\\State.hx"
		s.code_lengths = null;
		//line 35 "C:\\Users\\Dominik\\Brotli\\src\\decode\\State.hx"
		s.context_map_table = null;
		//line 37 "C:\\Users\\Dominik\\Brotli\\src\\decode\\State.hx"
		s.custom_dict = null;
		//line 38 "C:\\Users\\Dominik\\Brotli\\src\\decode\\State.hx"
		s.custom_dict_size = 0;
	}
	
	
}


