<?php

// Generated by Haxe 3.4.0
class encode_prefix_PrefixCodeRange {
	public function __construct($offset, $nbits) {
		if(!php_Boot::$skip_constructor) {
		$this->offset = $offset;
		$this->nbits = $nbits;
	}}
	public $offset;
	public $nbits;
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return 'encode.prefix.PrefixCodeRange'; }
}
