// Generated by Haxe 3.4.0
package decode.huffman;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class HuffmanTreeGroup extends haxe.lang.HxObject
{
	public HuffmanTreeGroup(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public HuffmanTreeGroup()
	{
		//line 17 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
		decode.huffman.HuffmanTreeGroup.__hx_ctor_decode_huffman_HuffmanTreeGroup(this);
	}
	
	
	public static void __hx_ctor_decode_huffman_HuffmanTreeGroup(decode.huffman.HuffmanTreeGroup __hx_this)
	{
	}
	
	
	public int alphabet_size;
	
	public int num_htrees;
	
	public decode.huffman.HuffmanCode[] codes;
	
	public haxe.root.Array<decode.huffman.HuffmanCode[]> htrees;
	
	public haxe.root.Array<java.lang.Object> htrees_off;
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
		{
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
			boolean __temp_executeDef1 = true;
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
			switch (field.hashCode())
			{
				case 1328902150:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					if (field.equals("num_htrees")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						this.num_htrees = ((int) (value) );
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						return value;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					break;
				}
				
				
				case -1663778227:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					if (field.equals("alphabet_size")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						this.alphabet_size = ((int) (value) );
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						return value;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					break;
				}
				
				
			}
			
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
			if (__temp_executeDef1) 
			{
				//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
		{
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
			boolean __temp_executeDef1 = true;
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
			switch (field.hashCode())
			{
				case 1087274845:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					if (field.equals("htrees_off")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						this.htrees_off = ((haxe.root.Array<java.lang.Object>) (value) );
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						return value;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					break;
				}
				
				
				case -1663778227:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					if (field.equals("alphabet_size")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						this.alphabet_size = ((int) (haxe.lang.Runtime.toInt(value)) );
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						return value;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					break;
				}
				
				
				case -1206910675:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					if (field.equals("htrees")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						this.htrees = ((haxe.root.Array<decode.huffman.HuffmanCode[]>) (value) );
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						return value;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					break;
				}
				
				
				case 1328902150:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					if (field.equals("num_htrees")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						this.num_htrees = ((int) (haxe.lang.Runtime.toInt(value)) );
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						return value;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					break;
				}
				
				
				case 94834726:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					if (field.equals("codes")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						this.codes = ((decode.huffman.HuffmanCode[]) (value) );
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						return value;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					break;
				}
				
				
			}
			
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
			if (__temp_executeDef1) 
			{
				//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
		{
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
			boolean __temp_executeDef1 = true;
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
			switch (field.hashCode())
			{
				case 1087274845:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					if (field.equals("htrees_off")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						return this.htrees_off;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					break;
				}
				
				
				case -1663778227:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					if (field.equals("alphabet_size")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						return this.alphabet_size;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					break;
				}
				
				
				case -1206910675:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					if (field.equals("htrees")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						return this.htrees;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					break;
				}
				
				
				case 1328902150:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					if (field.equals("num_htrees")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						return this.num_htrees;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					break;
				}
				
				
				case 94834726:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					if (field.equals("codes")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						return this.codes;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					break;
				}
				
				
			}
			
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
			if (__temp_executeDef1) 
			{
				//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
		{
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
			boolean __temp_executeDef1 = true;
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
			switch (field.hashCode())
			{
				case 1328902150:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					if (field.equals("num_htrees")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						return ((double) (this.num_htrees) );
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					break;
				}
				
				
				case -1663778227:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					if (field.equals("alphabet_size")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
						return ((double) (this.alphabet_size) );
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
					break;
				}
				
				
			}
			
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
			if (__temp_executeDef1) 
			{
				//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
		baseArr.push("htrees_off");
		//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
		baseArr.push("htrees");
		//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
		baseArr.push("codes");
		//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
		baseArr.push("num_htrees");
		//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
		baseArr.push("alphabet_size");
		//line 9 "C:\\Users\\Dominik\\Brotli\\src\\decode\\huffman\\HuffmanTreeGroup.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


