// Generated by Haxe 3.4.0

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace decode.streams {
	public class BrotliOutput : global::haxe.lang.HxObject {
		
		public BrotliOutput(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public BrotliOutput() {
			global::decode.streams.BrotliOutput.__hx_ctor_decode_streams_BrotliOutput(this);
		}
		
		
		public static void __hx_ctor_decode_streams_BrotliOutput(global::decode.streams.BrotliOutput __hx_this) {
		}
		
		
		public object cb_;
		
		public object data_;
		
		public int data_off;
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 330992538:
					{
						this.data_off = ((int) (@value) );
						return @value;
					}
					
					
					case 1418202869:
					{
						this.data_ = ((object) (@value) );
						return @value;
					}
					
					
					case 4945120:
					{
						this.cb_ = ((object) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 330992538:
					{
						this.data_off = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						return @value;
					}
					
					
					case 1418202869:
					{
						this.data_ = ((object) (@value) );
						return @value;
					}
					
					
					case 4945120:
					{
						this.cb_ = ((object) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 330992538:
					{
						return this.data_off;
					}
					
					
					case 1418202869:
					{
						return this.data_;
					}
					
					
					case 4945120:
					{
						return this.cb_;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 330992538:
					{
						return ((double) (this.data_off) );
					}
					
					
					case 1418202869:
					{
						return ((double) (global::haxe.lang.Runtime.toDouble(this.data_)) );
					}
					
					
					case 4945120:
					{
						return ((double) (global::haxe.lang.Runtime.toDouble(this.cb_)) );
					}
					
					
					default:
					{
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override void __hx_getFields(global::Array<object> baseArr) {
			baseArr.push("data_off");
			baseArr.push("data_");
			baseArr.push("cb_");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}


