// Generated by Haxe 3.4.0

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace decode {
	public class Port : global::haxe.lang.HxObject {
		
		public Port(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Port() {
			global::decode.Port.__hx_ctor_decode_Port(this);
		}
		
		
		public static void __hx_ctor_decode_Port(global::decode.Port __hx_this) {
		}
		
		
		public static bool PREDICT_FALSE(bool x) {
			return x;
		}
		
		
		public static bool PREDICT_TRUE(bool x) {
			return x;
		}
		
		
		public static void BROTLI_DCHECK(bool x) {
		}
		
		
	}
}


