// Generated by Haxe 3.4.0
package encode.command;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Command extends haxe.lang.HxObject
{
	public Command(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Command()
	{
		//line 53 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		encode.command.Command.__hx_ctor_encode_command_Command(this);
	}
	
	
	public static void __hx_ctor_encode_command_Command(encode.command.Command __hx_this)
	{
		//line 17 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		__hx_this.dist_extra_ = new haxe.root.Array<java.lang.Object>();
		//line 16 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		__hx_this.cmd_extra_ = new haxe.root.Array<java.lang.Object>();
		//line 15 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		__hx_this.dist_prefix_ = new haxe.root.Array<java.lang.Object>();
		//line 14 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		__hx_this.cmd_prefix_ = new haxe.root.Array<java.lang.Object>();
	}
	
	
	public int insert_len_;
	
	public int copy_len_;
	
	public haxe.root.Array<java.lang.Object> cmd_prefix_;
	
	public haxe.root.Array<java.lang.Object> dist_prefix_;
	
	public haxe.root.Array<java.lang.Object> cmd_extra_;
	
	public haxe.root.Array<java.lang.Object> dist_extra_;
	
	public void Command0()
	{
	}
	
	
	public void Command4(int insertlen, int copylen, int copylen_code, int distance_code)
	{
		//line 23 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		this.insert_len_ = insertlen;
		//line 23 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		this.copy_len_ = copylen;
		//line 24 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		encode.Command_functions.GetDistCode(distance_code, this.dist_prefix_, this.dist_extra_);
		//line 25 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		encode.Command_functions.GetLengthCode(insertlen, copylen_code, ((int) (haxe.lang.Runtime.toInt(this.dist_prefix_.__get(0))) ), this.cmd_prefix_, this.cmd_extra_);
	}
	
	
	public void Command1(int insertlen)
	{
		//line 30 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		this.insert_len_ = insertlen;
		//line 30 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		this.copy_len_ = 0;
		//line 30 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		this.dist_prefix_.__set(0, 16);
		//line 30 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		this.dist_extra_.__set(0, 0);
		//line 31 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		encode.Command_functions.GetLengthCode(insertlen, 4, ((int) (haxe.lang.Runtime.toInt(this.dist_prefix_.__get(0))) ), this.cmd_prefix_, this.cmd_extra_);
	}
	
	
	public int DistanceCode()
	{
		//line 35 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		int a = ((int) (haxe.lang.Runtime.toInt(this.dist_prefix_.__get(0))) );
		//line 35 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		boolean bNeg = ( ((int) (a) ) < 0 );
		//line 35 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		if (( (( false != bNeg )) ? (false) : (( ((int) (16) ) > ((int) (a) ) )) )) 
		{
			//line 36 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
			return ((int) (haxe.lang.Runtime.toInt(this.dist_prefix_.__get(0))) );
		}
		
		//line 38 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		int nbits = ( ((int) (haxe.lang.Runtime.toInt(this.dist_extra_.__get(0))) ) >>> 24 );
		//line 39 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		int extra = ( ((int) (haxe.lang.Runtime.toInt(this.dist_extra_.__get(0))) ) & ((int) (16777215) ) );
		//line 40 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		int prefix = ( ((int) (( ((int) (haxe.lang.Runtime.toInt(this.dist_prefix_.__get(0))) ) - ((int) (12) ) )) ) - ((int) (( 2 * nbits )) ) );
		//line 41 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		return ( ( (( prefix << nbits )) + extra ) + 12 );
	}
	
	
	public int DistanceContext()
	{
		//line 45 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		int c = ( ((int) (haxe.lang.Runtime.toInt(this.cmd_prefix_.__get(0))) ) & ((int) (7) ) );
		//line 46 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		int r = ( ((int) (haxe.lang.Runtime.toInt(this.cmd_prefix_.__get(0))) ) >>> 6 );
		//line 47 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		if (( (( ( ( ( r == 0 ) || ( r == 2 ) ) || ( r == 4 ) ) || ( r == 7 ) )) && ( c <= 2 ) )) 
		{
			//line 48 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
			return c;
		}
		
		//line 50 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		return 3;
	}
	
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		{
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
			boolean __temp_executeDef1 = true;
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
			switch (field.hashCode())
			{
				case 1505430388:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("copy_len_")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						this.copy_len_ = ((int) (value) );
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						return value;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
				case -103390544:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("insert_len_")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						this.insert_len_ = ((int) (value) );
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						return value;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
			}
			
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
			if (__temp_executeDef1) 
			{
				//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		{
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
			boolean __temp_executeDef1 = true;
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
			switch (field.hashCode())
			{
				case 1557550856:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("dist_extra_")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						this.dist_extra_ = ((haxe.root.Array<java.lang.Object>) (value) );
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						return value;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
				case -103390544:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("insert_len_")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						this.insert_len_ = ((int) (haxe.lang.Runtime.toInt(value)) );
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						return value;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
				case -2112195340:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("cmd_extra_")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						this.cmd_extra_ = ((haxe.root.Array<java.lang.Object>) (value) );
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						return value;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
				case 1505430388:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("copy_len_")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						this.copy_len_ = ((int) (haxe.lang.Runtime.toInt(value)) );
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						return value;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
				case 2026065524:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("dist_prefix_")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						this.dist_prefix_ = ((haxe.root.Array<java.lang.Object>) (value) );
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						return value;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
				case -66916856:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("cmd_prefix_")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						this.cmd_prefix_ = ((haxe.root.Array<java.lang.Object>) (value) );
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						return value;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
			}
			
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
			if (__temp_executeDef1) 
			{
				//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		{
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
			boolean __temp_executeDef1 = true;
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
			switch (field.hashCode())
			{
				case 1947110362:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("DistanceContext")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "DistanceContext")) );
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
				case -103390544:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("insert_len_")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						return this.insert_len_;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
				case -824442974:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("DistanceCode")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "DistanceCode")) );
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
				case 1505430388:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("copy_len_")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						return this.copy_len_;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
				case -537891226:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("Command1")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "Command1")) );
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
				case -66916856:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("cmd_prefix_")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						return this.cmd_prefix_;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
				case -537891223:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("Command4")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "Command4")) );
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
				case 2026065524:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("dist_prefix_")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						return this.dist_prefix_;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
				case -537891227:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("Command0")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "Command0")) );
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
				case -2112195340:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("cmd_extra_")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						return this.cmd_extra_;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
				case 1557550856:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("dist_extra_")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						return this.dist_extra_;
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
			}
			
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
			if (__temp_executeDef1) 
			{
				//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		{
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
			boolean __temp_executeDef1 = true;
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
			switch (field.hashCode())
			{
				case 1505430388:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("copy_len_")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						return ((double) (this.copy_len_) );
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
				case -103390544:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("insert_len_")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						return ((double) (this.insert_len_) );
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
			}
			
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
			if (__temp_executeDef1) 
			{
				//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, haxe.root.Array dynargs)
	{
		//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		{
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
			boolean __temp_executeDef1 = true;
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
			switch (field.hashCode())
			{
				case 1947110362:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("DistanceContext")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						return this.DistanceContext();
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
				case -537891227:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("Command0")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						this.Command0();
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
				case -824442974:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("DistanceCode")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						return this.DistanceCode();
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
				case -537891223:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("Command4")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						this.Command4(((int) (haxe.lang.Runtime.toInt(dynargs.__get(0))) ), ((int) (haxe.lang.Runtime.toInt(dynargs.__get(1))) ), ((int) (haxe.lang.Runtime.toInt(dynargs.__get(2))) ), ((int) (haxe.lang.Runtime.toInt(dynargs.__get(3))) ));
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
				case -537891226:
				{
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					if (field.equals("Command1")) 
					{
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						__temp_executeDef1 = false;
						//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
						this.Command1(((int) (haxe.lang.Runtime.toInt(dynargs.__get(0))) ));
					}
					
					//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
					break;
				}
				
				
			}
			
			//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
			if (__temp_executeDef1) 
			{
				//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		return null;
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		baseArr.push("dist_extra_");
		//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		baseArr.push("cmd_extra_");
		//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		baseArr.push("dist_prefix_");
		//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		baseArr.push("cmd_prefix_");
		//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		baseArr.push("copy_len_");
		//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		baseArr.push("insert_len_");
		//line 9 "C:\\Users\\Dominik\\Brotli\\src\\encode\\command\\Command.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


